package bench

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// RunRecord is one measured profile run. Durations live here (and in
// console output) but never in Markdown: wall-clock is environment noise
// and would break freshness gating.
type RunRecord struct {
	Profile         string        `json:"profile"`
	DurationSeconds float64       `json:"duration_seconds"`
	Result          ProfileResult `json:"result"`
}

// Report is the full JSON envelope for `bench --format json`.
type Report struct {
	Target  string      `json:"target"`
	Runs    int         `json:"runs"`
	Records []RunRecord `json:"records"`
}

// RenderJSON serializes a benchmark report deterministically.
func RenderJSON(rep Report) (string, error) {
	data, err := json.MarshalIndent(rep, "", "  ")
	if err != nil {
		return "", err
	}
	return string(data) + "\n", nil
}

// outcomeCell renders one table cell for a signal outcome.
func outcomeCell(o SignalOutcome) string {
	switch o.Verdict {
	case VerdictOK:
		if o.Outcome == OutcomeHIT {
			return "✓ HIT"
		}
		return "○ expected miss"
	case VerdictSurpriseHit:
		return "✓ HIT (unexpected)"
	default:
		return "✗ MISS"
	}
}

// RenderMarkdown renders the stable results table: signal rows in
// ground-truth order, per-profile columns, counts only (no timings, no
// finding IDs). Byte-identical for identical verdicts.
func RenderMarkdown(results []ProfileResult, target string, profiles []string, runs int) string {
	var b strings.Builder
	b.WriteString("| Signal |")
	for _, p := range profiles {
		fmt.Fprintf(&b, " %s |", p)
	}
	b.WriteString("\n| --- |")
	for range profiles {
		b.WriteString(" --- |")
	}
	b.WriteString("\n")
	var sigIDs []string
	byID := map[string][]SignalOutcome{}
	for _, r := range results {
		for _, o := range r.Signals {
			byID[o.SignalID] = append(byID[o.SignalID], o)
		}
	}
	if len(results) > 0 {
		for _, o := range results[0].Signals {
			sigIDs = append(sigIDs, o.SignalID)
		}
	}
	nonGating := false
	for _, id := range sigIDs {
		outs := byID[id]
		desc := ""
		gated := true
		if len(outs) > 0 {
			desc = outs[0].Description
			gated = outs[0].Gated
		}
		label := "`" + id + "`"
		if !gated {
			label += " †"
			nonGating = true
		}
		if desc != "" {
			label += " — " + desc
		}
		fmt.Fprintf(&b, "| %s |", label)
		for _, o := range outs {
			fmt.Fprintf(&b, " %s |", outcomeCell(o))
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")
	for _, r := range results {
		fmt.Fprintf(&b, "Findings (%s): %d total (%d confirmed / %d unconfirmed), %d unmatched.\n",
			r.Profile, r.Total, r.Confirmed, r.Unconfirmed, len(r.Unmatched))
	}
	b.WriteString("Unmatched findings are counted, never auto-labeled false positives.\n")
	if nonGating {
		b.WriteString("† non-gating: measured and shown, excluded from freshness checks until its flakiness is root-caused.\n")
	}
	fmt.Fprintf(&b, "\n_Generated by `anpu bench --target %s --profiles %s` (table shows run 1 of %d; timings excluded for stability; full per-run detail in the JSON artifact)._\n",
		target, strings.Join(profiles, ","), runs)
	return b.String()
}

// RenderTable renders a human console summary (not gated; may vary).
func RenderTable(results []ProfileResult, durations []float64) string {
	var b strings.Builder
	for i, r := range results {
		dur := 0.0
		if i < len(durations) {
			dur = durations[i]
		}
		fmt.Fprintf(&b, "%s: %d findings (%d confirmed / %d unconfirmed) in %.1fs\n",
			r.Profile, r.Total, r.Confirmed, r.Unconfirmed, dur)
		var cats []string
		for c := range r.ByCategory {
			cats = append(cats, c)
		}
		sort.Strings(cats)
		for _, c := range cats {
			fmt.Fprintf(&b, "  %-22s %d\n", c, r.ByCategory[c])
		}
		for _, o := range r.Signals {
			fmt.Fprintf(&b, "  [%s] %-16s expected %-13s (%d matched)\n",
				o.Verdict, o.SignalID, o.Expected, len(o.Matched))
		}
		fmt.Fprintf(&b, "  unmatched: %d\n", len(r.Unmatched))
	}
	return b.String()
}

// sectionBounds locates the marked freshness section in a document.
func sectionBounds(doc string) (start, end int, err error) {
	start = strings.Index(doc, MarkerStart)
	end = strings.Index(doc, MarkerEnd)
	if start < 0 || end < 0 || end < start {
		return 0, 0, fmt.Errorf("freshness markers %q / %q not found (or out of order)", MarkerStart, MarkerEnd)
	}
	return start, end + len(MarkerEnd), nil
}

// normalizeForCheck reduces a rendered table to its gate-relevant lines.
// Two classes of lines are excluded, for opposite reasons:
//   - "Findings (...)" count lines wobble run to run with
//     timing-sensitive discovery; signal verdicts are the load-bearing
//     content. Counts stay in the document as indicative context.
//   - "†" lines (non-gating signal rows and their footnote) are measured
//     and shown but excluded from the gate until their flakiness is
//     root-caused; gating them would fail CI on known-unstable signals.
func normalizeForCheck(s string) string {
	var kept []string
	for _, line := range strings.Split(s, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "Findings (") {
			continue
		}
		if strings.Contains(trimmed, "†") {
			continue
		}
		kept = append(kept, strings.TrimRight(line, " \t"))
	}
	return strings.TrimSpace(strings.Join(kept, "\n"))
}

// CheckSection verifies the marked section of a file equals generated
// output (whitespace-trimmed, counts-normalized). CI uses this as the
// freshness gate.
func CheckSection(path, generated string) error {
	raw, err := os.ReadFile(path) // #nosec G304 -- operator-specified docs path.
	if err != nil {
		return err
	}
	doc := string(raw)
	start, end, err := sectionBounds(doc)
	if err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	current := normalizeForCheck(doc[start:end])
	want := normalizeForCheck(MarkerStart + "\n" + strings.TrimSpace(generated) + "\n" + MarkerEnd)
	if current != want {
		return fmt.Errorf("%s: benchmark table is stale — regenerate with `anpu bench --refresh-docs %s` and commit the result", path, path)
	}
	return nil
}

// RefreshSection replaces the marked section of a file with generated
// output, preserving all surrounding prose.
func RefreshSection(path, generated string) error {
	raw, err := os.ReadFile(path) // #nosec G304 -- operator-specified docs path.
	if err != nil {
		return err
	}
	doc := string(raw)
	start, end, err := sectionBounds(doc)
	if err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	replacement := MarkerStart + "\n" + strings.TrimSpace(generated) + "\n" + MarkerEnd
	out := doc[:start] + replacement + doc[end:]
	if !strings.HasSuffix(out, "\n") {
		out += "\n"
	}
	return os.WriteFile(path, []byte(out), 0o600)
}
